package Frames;

import java.util.Random;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import Frames.Tienda;
import misClases.*;

public class Almacen extends javax.swing.JFrame {

    /**
     * Creates new form Almacen
     */
    public Almacen() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelAlmacen = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        textFieldNombre = new javax.swing.JTextField();
        textFieldPrecio = new javax.swing.JTextField();
        textFieldCantidad = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablaAlmacen = new javax.swing.JTable();
        ButtonBuscar = new javax.swing.JButton();
        ButtonQuitar = new javax.swing.JButton();
        ComboBoxSeccion = new javax.swing.JComboBox<>();
        ComboBoxMarca = new javax.swing.JComboBox<>();
        ButtonAgregar = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        ButtonTiendaPasar = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        PanelAlmacen.setBackground(new java.awt.Color(255, 204, 0));
        PanelAlmacen.setForeground(new java.awt.Color(102, 0, 102));
        PanelAlmacen.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/LogoSinFondoResized.png"))); // NOI18N
        PanelAlmacen.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 0, 280, 80));

        textFieldNombre.setPreferredSize(new java.awt.Dimension(200, 200));
        PanelAlmacen.add(textFieldNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 90, 160, 30));

        textFieldPrecio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldPrecioActionPerformed(evt);
            }
        });
        PanelAlmacen.add(textFieldPrecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 140, 60, -1));
        PanelAlmacen.add(textFieldCantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 90, 40, -1));

        jLabel4.setFont(new java.awt.Font("Yu Gothic UI", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 0, 102));
        jLabel4.setText("Marca");
        PanelAlmacen.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 140, 60, -1));

        jLabel5.setFont(new java.awt.Font("Yu Gothic UI", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(102, 0, 102));
        jLabel5.setText("Seccion");
        PanelAlmacen.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 140, -1, -1));

        jLabel6.setFont(new java.awt.Font("Yu Gothic UI", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(102, 0, 102));
        jLabel6.setText("Precio");
        PanelAlmacen.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, -1, -1));

        jLabel7.setFont(new java.awt.Font("Yu Gothic UI", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(102, 0, 102));
        jLabel7.setText("Cantidad");
        PanelAlmacen.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 90, -1, -1));

        jLabel8.setFont(new java.awt.Font("Yu Gothic UI", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(102, 0, 102));
        jLabel8.setText("Nombre");
        PanelAlmacen.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, -1, -1));

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        TablaAlmacen.setBackground(new java.awt.Color(255, 255, 255));
        TablaAlmacen.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        TablaAlmacen.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Nombre", "Marca", "Cantidad", "Seccion", "Precio"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.Double.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        TablaAlmacen.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_NEXT_COLUMN);
        TablaAlmacen.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        TablaAlmacen.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        TablaAlmacen.setShowGrid(true);
        jScrollPane1.setViewportView(TablaAlmacen);

        PanelAlmacen.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, 780, 180));

        ButtonBuscar.setText("Buscar Producto");
        PanelAlmacen.add(ButtonBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 200, -1, -1));

        ButtonQuitar.setText("Quitar Producto");
        PanelAlmacen.add(ButtonQuitar, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 200, -1, -1));

        ComboBoxSeccion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Confitería", "Bebidas", "Lacteos", "Comidas" }));
        PanelAlmacen.add(ComboBoxSeccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 140, -1, -1));

        ComboBoxMarca.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nestle", "Kraft", "Field", "D'onofrio" }));
        PanelAlmacen.add(ComboBoxMarca, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 140, -1, -1));

        ButtonAgregar.setText("Agregar Producto");
        ButtonAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonAgregarActionPerformed(evt);
            }
        });
        PanelAlmacen.add(ButtonAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 200, -1, -1));

        jButton1.setText("Burbuja");
        PanelAlmacen.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 200, 80, -1));

        jButton2.setText("Seleccion");
        PanelAlmacen.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 200, -1, -1));

        jButton3.setText("Insercion");
        PanelAlmacen.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, -1, -1));

        ButtonTiendaPasar.setText("Pasar producto a tienda");
        ButtonTiendaPasar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonTiendaPasarActionPerformed(evt);
            }
        });
        PanelAlmacen.add(ButtonTiendaPasar, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 140, -1, -1));

        jButton4.setText("IR A TIENDA");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        PanelAlmacen.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 200, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelAlmacen, javax.swing.GroupLayout.DEFAULT_SIZE, 818, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelAlmacen, javax.swing.GroupLayout.PREFERRED_SIZE, 451, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textFieldPrecioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldPrecioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldPrecioActionPerformed

    private void ButtonAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonAgregarActionPerformed
        /*
        Random random = new Random();
        int codigo = random.nextInt(9000) + 1000;
        String nombre = textFieldNombre.getText();
        String marca = ComboBoxMarca.getSelectedItem().toString();
        String seccion = ComboBoxSeccion.getSelectedItem().toString();
        double precio = Double.parseDouble(textFieldPrecio.getText());
        int cantidad = Integer.parseInt(textFieldCantidad.getText());

        Object[] fila = {codigo, nombre, marca, cantidad, seccion, precio};
        DefaultTableModel model = (DefaultTableModel) TablaAlmacen.getModel();
        model.addRow(fila);
        */
    }//GEN-LAST:event_ButtonAgregarActionPerformed

    private void ButtonTiendaPasarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonTiendaPasarActionPerformed
        // TODO add your handling code here:
        int filaSeleccionada = TablaAlmacen.getSelectedRow();
        Tienda tienda = new Tienda();
        tienda.setVisible(true);
        DefaultTableModel model = (DefaultTableModel) tienda.TablaTienda.getModel();
        model.addRow(new Object[]{TablaAlmacen.getValueAt(filaSeleccionada, 0), TablaAlmacen.getValueAt(filaSeleccionada, 1), TablaAlmacen.getValueAt(filaSeleccionada, 2), TablaAlmacen.getValueAt(filaSeleccionada, 3),TablaAlmacen.getValueAt(filaSeleccionada, 4),TablaAlmacen.getValueAt(filaSeleccionada, 5),});
    }//GEN-LAST:event_ButtonTiendaPasarActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        Tienda tienda = new Tienda();
        tienda.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Almacen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Almacen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Almacen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Almacen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Almacen().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonAgregar;
    private javax.swing.JButton ButtonBuscar;
    private javax.swing.JButton ButtonQuitar;
    private javax.swing.JButton ButtonTiendaPasar;
    private javax.swing.JComboBox<String> ComboBoxMarca;
    private javax.swing.JComboBox<String> ComboBoxSeccion;
    private javax.swing.JPanel PanelAlmacen;
    private javax.swing.JTable TablaAlmacen;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField textFieldCantidad;
    private javax.swing.JTextField textFieldNombre;
    private javax.swing.JTextField textFieldPrecio;
    // End of variables declaration//GEN-END:variables
}