package com.mycompany.avanceproyectofinalaed_maven.Frames.Paneles_Tienda.Vistas;

import java.awt.Color;
import javax.swing.JLabel;
import javax.swing.JPanel;

/**
 *
 * @author rvill
 */
public class Tienda extends javax.swing.JFrame {

    /**
     * Creates new form Tienda
     */
    
         Color colorFondoIngresoBtn = new Color(255, 0, 255);
         Color colorLetraIngresoBtn=  new Color(255, 255, 255);
         
          Color colorFondoSalidaBtn = new Color(255, 255, 255);
         Color colorLetraSalidaBtn= new Color(255, 0, 255);
    public Tienda() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        EtiquetaBtn = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        CampoBuscador = new javax.swing.JTextField();
        BotonBuscador = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        Sidebar_panel = new javax.swing.JPanel();
        inicio_PanelBtn = new javax.swing.JPanel();
        inicio_jlabel = new javax.swing.JLabel();
        productos_PanelBtn = new javax.swing.JPanel();
        producto_jlabel = new javax.swing.JLabel();
        carrito_PanelBtn = new javax.swing.JPanel();
        carrito_jlabel = new javax.swing.JLabel();
        panel_hojas = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                formInputMethodTextChanged(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 204, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        EtiquetaBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/etiqueta_flecha_morada.PNG"))); // NOI18N
        EtiquetaBtn.setText("jLabel2");
        EtiquetaBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        EtiquetaBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EtiquetaBtnMouseClicked(evt);
            }
        });
        jPanel1.add(EtiquetaBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 150, 83, 39));

        jPanel2.setBackground(new java.awt.Color(102, 0, 102));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logomenoschico.PNG"))); // NOI18N

        CampoBuscador.setForeground(new java.awt.Color(153, 153, 153));
        CampoBuscador.setText("Buscar productos");
        CampoBuscador.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        CampoBuscador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CampoBuscadorActionPerformed(evt);
            }
        });

        BotonBuscador.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/search(smaller).PNG"))); // NOI18N

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/carritoResized.PNG"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(CampoBuscador, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BotonBuscador)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton2)
                .addContainerGap(166, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 10, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton2)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(CampoBuscador, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(BotonBuscador)))
                .addGap(20, 20, 20))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 120));

        Sidebar_panel.setBackground(new java.awt.Color(255, 255, 255));

        inicio_PanelBtn.setBackground(new java.awt.Color(255, 255, 255));
        inicio_PanelBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        inicio_PanelBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                inicio_PanelBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                inicio_PanelBtnMouseExited(evt);
            }
        });

        inicio_jlabel.setBackground(new java.awt.Color(102, 0, 102));
        inicio_jlabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        inicio_jlabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        inicio_jlabel.setText("Inicio");
        inicio_jlabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout inicio_PanelBtnLayout = new javax.swing.GroupLayout(inicio_PanelBtn);
        inicio_PanelBtn.setLayout(inicio_PanelBtnLayout);
        inicio_PanelBtnLayout.setHorizontalGroup(
            inicio_PanelBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(inicio_jlabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        inicio_PanelBtnLayout.setVerticalGroup(
            inicio_PanelBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(inicio_jlabel, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
        );

        productos_PanelBtn.setBackground(new java.awt.Color(255, 255, 255));
        productos_PanelBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        productos_PanelBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                productos_PanelBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                productos_PanelBtnMouseExited(evt);
            }
        });

        producto_jlabel.setBackground(new java.awt.Color(102, 0, 102));
        producto_jlabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        producto_jlabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        producto_jlabel.setText("Productos");
        producto_jlabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout productos_PanelBtnLayout = new javax.swing.GroupLayout(productos_PanelBtn);
        productos_PanelBtn.setLayout(productos_PanelBtnLayout);
        productos_PanelBtnLayout.setHorizontalGroup(
            productos_PanelBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(producto_jlabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        productos_PanelBtnLayout.setVerticalGroup(
            productos_PanelBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(producto_jlabel, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
        );

        carrito_PanelBtn.setBackground(new java.awt.Color(255, 255, 255));
        carrito_PanelBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        carrito_PanelBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                carrito_PanelBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                carrito_PanelBtnMouseExited(evt);
            }
        });

        carrito_jlabel.setBackground(new java.awt.Color(102, 0, 102));
        carrito_jlabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        carrito_jlabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        carrito_jlabel.setText("Carrito");
        carrito_jlabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout carrito_PanelBtnLayout = new javax.swing.GroupLayout(carrito_PanelBtn);
        carrito_PanelBtn.setLayout(carrito_PanelBtnLayout);
        carrito_PanelBtnLayout.setHorizontalGroup(
            carrito_PanelBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(carrito_jlabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        carrito_PanelBtnLayout.setVerticalGroup(
            carrito_PanelBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(carrito_jlabel, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout Sidebar_panelLayout = new javax.swing.GroupLayout(Sidebar_panel);
        Sidebar_panel.setLayout(Sidebar_panelLayout);
        Sidebar_panelLayout.setHorizontalGroup(
            Sidebar_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(inicio_PanelBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(productos_PanelBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(carrito_PanelBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        Sidebar_panelLayout.setVerticalGroup(
            Sidebar_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Sidebar_panelLayout.createSequentialGroup()
                .addGap(106, 106, 106)
                .addComponent(inicio_PanelBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(productos_PanelBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(carrito_PanelBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(202, Short.MAX_VALUE))
        );

        jPanel1.add(Sidebar_panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 190, 500));

        panel_hojas.setBackground(new java.awt.Color(255, 204, 0));

        javax.swing.GroupLayout panel_hojasLayout = new javax.swing.GroupLayout(panel_hojas);
        panel_hojas.setLayout(panel_hojasLayout);
        panel_hojasLayout.setHorizontalGroup(
            panel_hojasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 610, Short.MAX_VALUE)
        );
        panel_hojasLayout.setVerticalGroup(
            panel_hojasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
        );

        jPanel1.add(panel_hojas, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 120, 610, 500));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 618, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_formInputMethodTextChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_formInputMethodTextChanged

    private void CampoBuscadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CampoBuscadorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CampoBuscadorActionPerformed

    private void EtiquetaBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EtiquetaBtnMouseClicked
     
    }//GEN-LAST:event_EtiquetaBtnMouseClicked

    private void inicio_PanelBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_inicio_PanelBtnMouseEntered
  
        inicio_PanelBtn.setBackground(colorFondoIngresoBtn);
        inicio_jlabel.setBackground(colorLetraIngresoBtn);
    }//GEN-LAST:event_inicio_PanelBtnMouseEntered

    private void productos_PanelBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_productos_PanelBtnMouseEntered
 
        productos_PanelBtn.setBackground(colorFondoIngresoBtn);
        producto_jlabel.setBackground(colorLetraIngresoBtn);    }//GEN-LAST:event_productos_PanelBtnMouseEntered

    private void carrito_PanelBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_carrito_PanelBtnMouseEntered
     carrito_PanelBtn.setBackground(colorFondoIngresoBtn);
        carrito_jlabel.setBackground(colorLetraIngresoBtn); 
    }//GEN-LAST:event_carrito_PanelBtnMouseEntered

    private void inicio_PanelBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_inicio_PanelBtnMouseExited
     inicio_PanelBtn.setBackground(colorFondoSalidaBtn);
        inicio_jlabel.setBackground(colorLetraSalidaBtn);
    }//GEN-LAST:event_inicio_PanelBtnMouseExited

    private void productos_PanelBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_productos_PanelBtnMouseExited
     productos_PanelBtn.setBackground(colorFondoSalidaBtn);
        producto_jlabel.setBackground(colorLetraSalidaBtn);
    }//GEN-LAST:event_productos_PanelBtnMouseExited

    private void carrito_PanelBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_carrito_PanelBtnMouseExited
 carrito_PanelBtn.setBackground(colorFondoSalidaBtn);
        carrito_jlabel.setBackground(colorLetraSalidaBtn);
    }//GEN-LAST:event_carrito_PanelBtnMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tienda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tienda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tienda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tienda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tienda().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonBuscador;
    private javax.swing.JTextField CampoBuscador;
    private javax.swing.JLabel EtiquetaBtn;
    private javax.swing.JPanel Sidebar_panel;
    private javax.swing.JPanel carrito_PanelBtn;
    private javax.swing.JLabel carrito_jlabel;
    private javax.swing.JPanel inicio_PanelBtn;
    private javax.swing.JLabel inicio_jlabel;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel panel_hojas;
    private javax.swing.JLabel producto_jlabel;
    private javax.swing.JPanel productos_PanelBtn;
    // End of variables declaration//GEN-END:variables

    public JLabel getEtiquetaBtn() {
        return EtiquetaBtn;
    }

    public JPanel getSidebar_panel() {
        return Sidebar_panel;
    }

    public JLabel getCarrito_jlabel() {
        return carrito_jlabel;
    }

    public JLabel getInicio_jlabel() {
        return inicio_jlabel;
    }

    public JLabel getProducto_jlabel() {
        return producto_jlabel;
    }

    public JPanel getPanel_hojas() {
        return panel_hojas;
    }

    public JPanel getCarrito_PanelBtn() {
        return carrito_PanelBtn;
    }

    public JPanel getInicio_PanelBtn() {
        return inicio_PanelBtn;
    }

    public JPanel getProductos_PanelBtn() {
        return productos_PanelBtn;
    }




}
