/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */

package com.mycompany.avanceproyectofinalaed_maven.Frames.Paneles_Tienda.Vistas;

import javax.swing.JLabel;
import javax.swing.JPanel;

/**
 *
 * @author Jvalentino
 */
public class vista_producto_item extends javax.swing.JPanel {

    /** Creates new form vista_producto_item */
    public vista_producto_item() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        imagen_producto = new javax.swing.JLabel();
        nombre_producto = new javax.swing.JLabel();
        precio_producto = new javax.swing.JLabel();
        btn_Agregar_carrito = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        setMinimumSize(new java.awt.Dimension(0, 0));
        setName(""); // NOI18N
        setPreferredSize(new java.awt.Dimension(200, 200));
        setLayout(new java.awt.GridLayout(4, 1));

        imagen_producto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        imagen_producto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/carritoResized.PNG"))); // NOI18N
        imagen_producto.setText("e");
        imagen_producto.setToolTipText("");
        imagen_producto.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        imagen_producto.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        add(imagen_producto);

        nombre_producto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nombre_producto.setText("jLabel1");
        nombre_producto.setToolTipText("");
        nombre_producto.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        nombre_producto.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        add(nombre_producto);

        precio_producto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        precio_producto.setText("jLabel1");
        precio_producto.setToolTipText("");
        precio_producto.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        precio_producto.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        add(precio_producto);

        btn_Agregar_carrito.setBackground(new java.awt.Color(255, 0, 255));
        btn_Agregar_carrito.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_Agregar_carrito.setMinimumSize(new java.awt.Dimension(0, 0));
        btn_Agregar_carrito.setLayout(new java.awt.BorderLayout());

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Agregar");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_Agregar_carrito.add(jLabel1, java.awt.BorderLayout.CENTER);

        add(btn_Agregar_carrito);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel btn_Agregar_carrito;
    private javax.swing.JLabel imagen_producto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel nombre_producto;
    private javax.swing.JLabel precio_producto;
    // End of variables declaration//GEN-END:variables

    public JLabel getImagen_producto() {
        return imagen_producto;
    }

    public JLabel getNombre_producto() {
        return nombre_producto;
    }

    public JLabel getPrecio_producto() {
        return precio_producto;
    }

    public JPanel getBtn_Agregar_carrito() {
        return btn_Agregar_carrito;
    }

    public void setBtn_Agregar_carrito(JPanel btn_Agregar_carrito) {
        this.btn_Agregar_carrito = btn_Agregar_carrito;
    }

  



}
